static const char *RcsId = "$Id $";
//+=============================================================================
//
// file :         Andor3StateMachine.cpp
//
// description :  C++ source for the Andor3 and its alowed 
//                methods for commands and attributes
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL: $
//
// CVS only:
// $Source:  $
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <Andor3.h>
#include <Andor3Class.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace Andor3_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_adcGain_allowed
// 
// description : 	Read/Write allowed for adcGain attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_adcGain_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::INIT	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_adcRate_allowed
// 
// description : 	Read/Write allowed for adcRate attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_adcRate_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::INIT	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_electronicShutterMode_allowed
// 
// description : 	Read/Write allowed for electronicShutterMode attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_electronicShutterMode_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::INIT	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_temperatureSP_allowed
// 
// description : 	Read/Write allowed for temperatureSP attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_temperatureSP_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::INIT	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_temperature_allowed
// 
// description : 	Read/Write allowed for temperature attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_temperature_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::INIT	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_cooler_allowed
// 
// description : 	Read/Write allowed for cooler attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_cooler_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::INIT	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_coolingStatus_allowed
// 
// description : 	Read/Write allowed for coolingStatus attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_coolingStatus_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::INIT	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_adcGainStr_allowed
// 
// description : 	Read/Write allowed for adcGainStr attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_adcGainStr_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::INIT	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_adcRateStr_allowed
// 
// description : 	Read/Write allowed for adcRateStr attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_adcRateStr_allowed(Tango::AttReqType type)
{
	if (get_state() == Tango::INIT	||
		get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_electronicShutterModeStr_allowed
// 
// description : 	Read/Write allowed for electronicShutterModeStr attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_electronicShutterModeStr_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_bufferOverflow_allowed
// 
// description : 	Read/Write allowed for bufferOverflow attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_bufferOverflow_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_fanSpeed_allowed
// 
// description : 	Read/Write allowed for fanSpeed attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_fanSpeed_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_overlap_allowed
// 
// description : 	Read/Write allowed for overlap attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_overlap_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_spuriousNoiseFilter_allowed
// 
// description : 	Read/Write allowed for spuriousNoiseFilter attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_spuriousNoiseFilter_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_syncTriggering_allowed
// 
// description : 	Read/Write allowed for syncTriggering attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_syncTriggering_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_simpleGainControl_allowed
// 
// description : 	Read/Write allowed for simpleGainControl attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_simpleGainControl_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_simpleGainControlStr_allowed
// 
// description : 	Read/Write allowed for simpleGainControlStr attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_simpleGainControlStr_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_bytesPerPixel_allowed
// 
// description : 	Read/Write allowed for bytesPerPixel attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_bytesPerPixel_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_firmwareVersion_allowed
// 
// description : 	Read/Write allowed for firmwareVersion attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_firmwareVersion_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_frameRate_allowed
// 
// description : 	Read/Write allowed for frameRate attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_frameRate_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_frameRateMax_allowed
// 
// description : 	Read/Write allowed for frameRateMax attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_frameRateMax_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_frameRateMin_allowed
// 
// description : 	Read/Write allowed for frameRateMin attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_frameRateMin_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_fullRoiControl_allowed
// 
// description : 	Read/Write allowed for fullRoiControl attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_fullRoiControl_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_imageSize_allowed
// 
// description : 	Read/Write allowed for imageSize attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_imageSize_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_maxFrameRateTransfer_allowed
// 
// description : 	Read/Write allowed for maxFrameRateTransfer attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_maxFrameRateTransfer_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_readoutTime_allowed
// 
// description : 	Read/Write allowed for readoutTime attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_readoutTime_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Andor3::is_serialNumber_allowed
// 
// description : 	Read/Write allowed for serialNumber attribute.
//
//-----------------------------------------------------------------------------
bool Andor3::is_serialNumber_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================


}	// namespace Andor3_ns
